# Generated by Django 5.2.4 on 2025-08-22 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='detail',
            field=models.CharField(blank=True, default='따뜻함을 좋아하는 감성탐험가', max_length=255, verbose_name='회원설명'),
        ),
    ]
