# Generated by Django 5.2.4 on 2025-08-24 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='detail',
            field=models.CharField(blank=True, max_length=255, verbose_name='회원설명'),
        ),
    ]
