# Generated by Django 5.2.4 on 2025-09-25 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
