# Generated by Django 5.2.4 on 2025-08-19 15:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('community', '0003_bookmark'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInferenceSession',
            fields=[
                ('session_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('selected_emotions', models.ManyToManyField(to='community.emotion', verbose_name='선택된 감정들')),
                ('selected_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.location', verbose_name='선택된 동네')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '사용자 추론 세션',
                'verbose_name_plural': '사용자 추론 세션들',
                'db_table': 'user_inference_session',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InferenceRecommendation',
            fields=[
                ('recommendation_id', models.AutoField(primary_key=True, serialize=False)),
                ('gpt_recommendation_text', models.TextField(verbose_name='GPT 추천 텍스트')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='infer.userinferencesession')),
            ],
            options={
                'verbose_name': '추론 추천 결과',
                'verbose_name_plural': '추론 추천 결과들',
                'db_table': 'inference_recommendation',
                'ordering': ['-created_at'],
            },
        ),
    ]
