# Generated by Django 4.2.7 on 2025-08-23 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0006_merge_20250822_2114'),
        ('infer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inferencerecommendation',
            name='gpt_recommendation_text',
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('shop_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('image_url', models.TextField(blank=True, default='')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('emotions', models.ManyToManyField(related_name='infer_places', to='community.emotion')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='infer_places', to='community.location')),
            ],
            options={
                'db_table': 'infer_place',
            },
        ),
        migrations.CreateModel(
            name='AISummary',
            fields=[
                ('summary_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('summary', models.TextField(verbose_name='GPT 추천 텍스트')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_summary', to='infer.place')),
            ],
            options={
                'db_table': 'infer_ai_summary',
            },
        ),
        migrations.AddField(
            model_name='inferencerecommendation',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inference_recommendations', to='infer.place'),
        ),
    ]
