# Generated by Django 4.2.7 on 2025-08-23 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infer', '0002_remove_inferencerecommendation_gpt_recommendation_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aisummary',
            name='emotion_tags',
            field=models.JSONField(blank=True, default=list, verbose_name='생성된 감정 태그'),
        ),
        migrations.AddField(
            model_name='aisummary',
            name='reviews_snapshot',
            field=models.JSONField(blank=True, default=list, verbose_name='요약 생성 시점의 리뷰 스냅샷'),
        ),
        migrations.AddField(
            model_name='place',
            name='google_rating',
            field=models.FloatField(default=0.0, verbose_name='Google 평점'),
        ),
        migrations.AddField(
            model_name='place',
            name='place_types',
            field=models.JSONField(blank=True, default=list, verbose_name='Google 장소 타입'),
        ),
        migrations.AddField(
            model_name='place',
            name='reviews',
            field=models.JSONField(blank=True, default=list, verbose_name='Google 리뷰 데이터'),
        ),
    ]
