# Generated by Django 4.2.7 on 2025-08-23 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0006_merge_20250822_2114'),
        ('infer', '0003_aisummary_emotion_tags_aisummary_reviews_snapshot_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinferencesession',
            name='selected_location',
        ),
        migrations.AddField(
            model_name='userinferencesession',
            name='selected_location',
            field=models.ManyToManyField(to='community.location', verbose_name='선택된 동네들'),
        ),
    ]
