# Generated by Django 5.2.4 on 2025-08-24 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infer', '0004_remove_userinferencesession_selected_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='status',
            field=models.CharField(choices=[('operating', '운영중'), ('closed', '폐업함'), ('moved', '이전함')], default='operating', max_length=20, verbose_name='운영 상태'),
        ),
    ]
