# Generated by Django 5.2.4 on 2025-08-25 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infer', '0005_place_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='google_place_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
