# Generated by Django 5.2.4 on 2025-08-25 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infer', '0006_place_google_place_id'),
        ('recommendations', '0012_place_google_place_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aisummary',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='infer_ai_summary', to='recommendations.place'),
        ),
        migrations.AlterField(
            model_name='inferencerecommendation',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inference_recommendations', to='recommendations.place'),
        ),
        migrations.DeleteModel(
            name='Place',
        ),
    ]
