# Generated by Django 5.2.4 on 2025-08-13 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='emotion',
            fields=[
                ('emotion_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='location',
            fields=[
                ('location_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='memory',
            fields=[
                ('memory_id', models.AutoField(primary_key=True, serialize=False)),
                ('emotion_id', models.IntegerField()),
                ('location_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='image',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('image_url', models.URLField()),
                ('image_name', models.CharField(max_length=100)),
                ('memory_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='community.memory')),
            ],
        ),
    ]
