# Generated by Django 5.2.4 on 2025-08-13 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memory',
            name='emotion_id',
        ),
        migrations.AlterField(
            model_name='memory',
            name='location_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memories', to='community.location'),
        ),
        migrations.AddField(
            model_name='memory',
            name='emotion_id',
            field=models.ManyToManyField(to='community.emotion'),
        ),
    ]
