# Generated by Django 5.2.4 on 2025-08-22 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_bookmark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emotion',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
