# Generated by Django 5.2.4 on 2025-08-13 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_alter_image_image_name_alter_image_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='memory_id',
            field=models.ForeignKey(db_column='memory_id', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='community.memory'),
        ),
    ]
