# Generated by Django 5.2.4 on 2025-08-21 14:48

from django.db import migrations

def seed_data(apps, schema_editor):
    Emotion = apps.get_model("community", "Emotion")
    Location = apps.get_model("community", "Location")

    # Emotion seed
    emotions = ["정겨움", "편안함", "조용함", "활기참", "소박함","세심함"]
    for name in emotions:
        Emotion.objects.get_or_create(name=name)

    # Location seed
    locations = ["이태원", "한남동", "후암동", "효창동", "용문동","청파동","해방촌"]
    for name in locations:
        Location.objects.get_or_create(name=name)


def unseed_data(apps, schema_editor):
    Emotion = apps.get_model("community", "Emotion")
    Location = apps.get_model("community", "Location")

    # 필요하다면 롤백 시 삭제
    Emotion.objects.all().delete()
    Location.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0001_initial"),  # 초기 마이그레이션에 의존
    ]

    operations = [
        migrations.RunPython(seed_data, reverse_code=unseed_data),
    ]

