# Generated by Django 5.2.4 on 2025-08-21 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_bookmark'),
        ('community', '0004_auto_20250821_1448'),
    ]

    operations = [
    ]
