# Generated by Django 5.2.4 on 2025-08-13 22:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_alter_image_memory_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='memory_id',
        ),
        migrations.AddField(
            model_name='image',
            name='memory',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='community.memory'),
            preserve_default=False,
        ),
    ]
