# Generated by Django 5.2.4 on 2025-08-22 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_alter_emotion_name'),
        ('community', '0005_merge_0003_bookmark_0004_auto_20250821_1448'),
    ]

    operations = [
    ]
