# Generated by Django 5.2.4 on 2025-08-14 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0005_remove_image_memory_id_image_memory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memory',
            name='title',
        ),
    ]
