# Generated by Django 5.2.4 on 2025-08-15 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0007_alter_memory_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='memory',
            old_name='location_id',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='memory',
            old_name='user_id',
            new_name='user',
        ),
    ]
