# Generated by Django 5.2.4 on 2025-09-22 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0008_comment_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('board_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
