# Generated by Django 5.2.4 on 2025-09-22 13:16

from django.db import migrations

def seed_boards(apps, schema_editor):
    Board = apps.get_model("community", "Board")
    boards = ["제보", "홍보", "추억 기록"]
    for name in boards:
        Board.objects.get_or_create(name=name)


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0009_board'),
    ]

    operations = [
        migrations.RunPython(seed_boards, reverse_code=migrations.RunPython.noop),
    ]
