# Generated by Django 5.2.4 on 2025-09-22 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0010_seed_board'),
    ]

    operations = [
        migrations.AddField(
            model_name='memory',
            name='board',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memories', to='community.board'),
        ),
    ]
