# Generated by Django 5.2.4 on 2025-08-17 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('community', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeaerchShop',
            fields=[
                ('shop_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=50)),
                ('uptaenm', models.CharField(max_length=50)),
                ('emotion_id', models.ManyToManyField(to='community.emotion')),
            ],
        ),
    ]
