# Generated by Django 5.2.4 on 2025-08-17 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_initial'),
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SeaerchShop',
            new_name='SearchShop',
        ),
    ]
