"""
Django settings for spotal project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from decouple import config
import os
import environ


BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
env = environ.Env()
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))  # 경로 직접 지정


from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-^c*8d*pmfc^%&z@6c@8a=ilioa3_r6&gk94hrt5+*(fa**+u%z'

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG and ALLOWED_HOSTS are now configured below using environment variables


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'spotal',
    'rest_framework',
    'community',
    'storages',  # S3 스토리지 사용을 위한 앱
    'rest_framework.authtoken',
    'users',
    'recommendations',
    'search',
    'infer',
    'corsheaders',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware', 
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'spotal.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'spotal.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'ko-kr'

TIME_ZONE = 'Asia/Seoul'

USE_I18N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# S3 settings

# settings.py
AWS_STORAGE_BUCKET_NAME = env("AWS_STORAGE_BUCKET_NAME")
AWS_S3_REGION_NAME = env("AWS_S3_REGION_NAME", default="ap-northeast-2")

STORAGES = {
    "default": {
        "BACKEND": "storages.backends.s3.S3Storage",
        "OPTIONS": {
            "bucket_name": env("AWS_STORAGE_BUCKET_NAME"),
            "region_name": env("AWS_S3_REGION_NAME", default="ap-northeast-2"),
            "location": "media",
            "default_acl": None,         # 기본 ACL 없음
            "querystring_auth": False,   # presigned 말고 퍼블릭 URL
            "file_overwrite": False,     # 같은 파일명 덮어쓰기 방지
        },
    },
    "staticfiles": {
        "BACKEND": "storages.backends.s3.S3Storage",
        "OPTIONS": {
            "bucket_name": env("AWS_STORAGE_BUCKET_NAME"),
            "region_name": env("AWS_S3_REGION_NAME", default="ap-northeast-2"),
            "location": "static",
            "default_acl": None,
            "querystring_auth": False,   # 퍼블릭 URL
        },
    },
}
# Custom User Model
AUTH_USER_MODEL = 'users.User'

# Django REST Framework 설정
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        #'rest_framework_simplejwt.authentication.JWTAuthentication',
       # 'rest_framework.authentication.SessionAuthentication', # 세션으로 하면 로그인이 일부 안 되는 문제 발생 
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}

OPENAI_API_KEY = config('OPENAI_API_KEY')
#PUBLIC_DATA_API_KEY = config('PUBLIC_DATA_API_KEY')
GOOGLE_API_KEY = config('GOOGLE_API_KEY')



# authenticate()가 User 모델 인식 (없으면 None 반환)
AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",  
]

CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "http://spotal-fe-bucket.s3-website.ap-northeast-2.amazonaws.com",
    "https://spotal-fe-bucket.s3-website.ap-northeast-2.amazonaws.com",
]

CORS_ALLOW_CREDENTIALS = True

# 프로덕션 환경 설정
DEBUG = env('DEBUG', default=False)
SECRET_KEY = env('SECRET_KEY', default='django-insecure-^c*8d*pmfc^%&z@6c@8a=ilioa3_r6&gk94hrt5+*(fa**+u%z')
#ALLOWED_HOSTS = env('ALLOWED_HOSTS', default='13.124.195.6').split(',')
ALLOWED_HOSTS = ["*"]


