# Generated by Django 5.2.4 on 2025-08-18 04:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('shop_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('emotion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='places', to='community.emotion')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='places', to='community.location')),
            ],
            options={
                'db_table': 'place',
            },
        ),
        migrations.CreateModel(
            name='AISummary',
            fields=[
                ('summary_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('summary', models.TextField()),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summaries', to='recommendations.place')),
            ],
            options={
                'db_table': 'ai_summary',
            },
        ),
        migrations.CreateModel(
            name='SavedPlace',
            fields=[
                ('saved_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_records', to='recommendations.place')),
            ],
            options={
                'db_table': 'saved_place',
            },
        ),
    ]
