# Generated by Django 5.2.4 on 2025-08-18 04:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recommendations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='savedplace',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_places', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='savedplace',
            index=models.Index(fields=['user'], name='saved_place_user_id_9328b9_idx'),
        ),
        migrations.AddIndex(
            model_name='savedplace',
            index=models.Index(fields=['created_date'], name='saved_place_created_55ffe3_idx'),
        ),
        migrations.AddConstraint(
            model_name='savedplace',
            constraint=models.UniqueConstraint(fields=('shop', 'user'), name='uniq_user_shop_save'),
        ),
    ]
