# Generated by Django 5.2.4 on 2025-08-18 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aisummary',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_summary', to='recommendations.place'),
        ),
    ]
