# Generated by Django 5.2.4 on 2025-08-20 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0003_alter_aisummary_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='image_url',
            field=models.TextField(blank=True, default=''),
        ),
    ]
