# Generated by Django 5.2.4 on 2025-08-22 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_bookmark'),
        ('recommendations', '0005_aisummary_created_date_aisummary_modified_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='emotion',
        ),
        migrations.AddField(
            model_name='place',
            name='emotion',
            field=models.ManyToManyField(related_name='places', to='community.emotion'),
        ),
    ]
