# Generated by Django 5.2.4 on 2025-08-22 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0006_remove_place_emotion_place_emotion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='emotion',
            new_name='emotions',
        ),
    ]
