# Generated by Django 5.2.4 on 2025-08-22 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0007_rename_emotion_place_emotions'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedplace',
            name='summary_snapshot',
            field=models.TextField(blank=True, default=''),
        ),
    ]
