# Generated by Django 5.2.4 on 2025-08-23 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0008_savedplace_summary_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='status',
            field=models.CharField(default='recommended', max_length=50),
        ),
        migrations.AddField(
            model_name='savedplace',
            name='status',
            field=models.CharField(default='saved', max_length=50),
        ),
    ]
