# Generated by Django 5.2.4 on 2025-08-23 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0009_place_status_savedplace_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='status',
        ),
        migrations.RemoveField(
            model_name='savedplace',
            name='status',
        ),
    ]
