# Generated by Django 5.2.4 on 2025-08-24 19:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0010_remove_place_status_remove_savedplace_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='savedplace',
            name='uniq_user_shop_save',
        ),
        migrations.AddField(
            model_name='savedplace',
            name='rec',
            field=models.IntegerField(choices=[(1, '추천1'), (2, '추천2')], default=1),
        ),
        migrations.AddConstraint(
            model_name='savedplace',
            constraint=models.UniqueConstraint(fields=('shop', 'rec', 'user'), name='uniq_user_shop_rec_save'),
        ),
    ]
