# Generated by Django 5.2.4 on 2025-08-25 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0011_remove_savedplace_uniq_user_shop_save_savedplace_rec_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='google_place_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
