# Generated by Django 5.2.4 on 2025-08-25 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0012_place_google_place_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='google_rating',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='place_types',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='reviews',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='status',
            field=models.CharField(blank=True, choices=[('operating', '운영중'), ('closed', '폐업함'), ('moved', '이전함')], default='operating', max_length=20, null=True),
        ),
    ]
