# Generated by Django 5.2.4 on 2025-08-25 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0013_place_google_rating_place_place_types_place_reviews_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='image_url',
        ),
        migrations.AddField(
            model_name='place',
            name='photo_reference',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
    ]
